-- AlterTable
ALTER TABLE "company_settings" ADD COLUMN     "weight_energy_consumption" DECIMAL(5,2) NOT NULL DEFAULT 2.0,
ADD COLUMN     "weight_environmental_incidents" DECIMAL(5,2) NOT NULL DEFAULT 2.0,
ADD COLUMN     "weight_health_checkup_compliance" DECIMAL(5,2) NOT NULL DEFAULT 4.0,
ADD COLUMN     "weight_overdue_trainings" DECIMAL(5,2) NOT NULL DEFAULT 4.0,
ADD COLUMN     "weight_ppe_compliance_rate" DECIMAL(5,2) NOT NULL DEFAULT 4.0,
ADD COLUMN     "weight_ppe_observations" DECIMAL(5,2) NOT NULL DEFAULT 2.0,
ADD COLUMN     "weight_recordable_incidents" DECIMAL(5,2) NOT NULL DEFAULT 8.0,
ADD COLUMN     "weight_spills_incidents" DECIMAL(5,2) NOT NULL DEFAULT 2.0,
ADD COLUMN     "weight_upcoming_trainings" DECIMAL(5,2) NOT NULL DEFAULT 2.0,
ADD COLUMN     "weight_waste_disposed" DECIMAL(5,2) NOT NULL DEFAULT 2.0,
ADD COLUMN     "weight_waste_generated" DECIMAL(5,2) NOT NULL DEFAULT 2.0,
ADD COLUMN     "weight_water_consumption" DECIMAL(5,2) NOT NULL DEFAULT 2.0,
ADD COLUMN     "weight_water_quality_test" DECIMAL(5,2) NOT NULL DEFAULT 2.0,
ADD COLUMN     "weight_workforce_trained_percent" DECIMAL(5,2) NOT NULL DEFAULT 4.0,
ALTER COLUMN "weight_man_days" SET DEFAULT 2.0,
ALTER COLUMN "weight_safe_work_hours" SET DEFAULT 2.0,
ALTER COLUMN "weight_safety_induction" SET DEFAULT 2.0,
ALTER COLUMN "weight_tool_box_talk" SET DEFAULT 2.0,
ALTER COLUMN "weight_job_specific_training" SET DEFAULT 2.0,
ALTER COLUMN "weight_formal_safety_inspection" SET DEFAULT 2.0,
ALTER COLUMN "weight_non_compliance_raised" SET DEFAULT 4.0,
ALTER COLUMN "weight_non_compliance_close" SET DEFAULT 1.0,
ALTER COLUMN "weight_safety_observation_raised" SET DEFAULT 2.0,
ALTER COLUMN "weight_safety_observation_close" SET DEFAULT 1.0,
ALTER COLUMN "weight_work_permit_issued" SET DEFAULT 1.0,
ALTER COLUMN "weight_safe_work_method_statement" SET DEFAULT 1.0,
ALTER COLUMN "weight_emergency_mock_drills" SET DEFAULT 2.0,
ALTER COLUMN "weight_internal_audit" SET DEFAULT 2.0,
ALTER COLUMN "weight_near_miss_report" SET DEFAULT 8.0,
ALTER COLUMN "weight_first_aid_injury" SET DEFAULT 8.0,
ALTER COLUMN "weight_medical_treatment_injury" SET DEFAULT 8.0,
ALTER COLUMN "weight_lost_time_injury" SET DEFAULT 8.0;
