-- AlterTable
ALTER TABLE "safety_metrics" ADD COLUMN     "energy_consumption_actual" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN     "energy_consumption_score" DECIMAL(5,2),
ADD COLUMN     "energy_consumption_target" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN     "environment_score" DECIMAL(5,2) NOT NULL DEFAULT 0,
ADD COLUMN     "environmental_incidents_actual" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "environmental_incidents_score" DECIMAL(5,2),
ADD COLUMN     "environmental_incidents_target" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "health_checkup_compliance_actual" DECIMAL(5,2) NOT NULL DEFAULT 0,
ADD COLUMN     "health_checkup_compliance_score" DECIMAL(5,2),
ADD COLUMN     "health_checkup_compliance_target" DECIMAL(5,2) NOT NULL DEFAULT 100,
ADD COLUMN     "health_hygiene_score" DECIMAL(5,2) NOT NULL DEFAULT 0,
ADD COLUMN     "overdue_trainings_actual" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "overdue_trainings_score" DECIMAL(5,2),
ADD COLUMN     "overdue_trainings_target" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "ppe_compliance_rate_actual" DECIMAL(5,2) NOT NULL DEFAULT 0,
ADD COLUMN     "ppe_compliance_rate_score" DECIMAL(5,2),
ADD COLUMN     "ppe_compliance_rate_target" DECIMAL(5,2) NOT NULL DEFAULT 100,
ADD COLUMN     "ppe_compliance_score" DECIMAL(5,2) NOT NULL DEFAULT 0,
ADD COLUMN     "ppe_observations_actual" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "ppe_observations_score" DECIMAL(5,2),
ADD COLUMN     "ppe_observations_target" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "recordable_incidents_actual" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "recordable_incidents_score" DECIMAL(5,2),
ADD COLUMN     "recordable_incidents_target" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "spills_incidents_actual" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "spills_incidents_score" DECIMAL(5,2),
ADD COLUMN     "spills_incidents_target" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "upcoming_trainings_actual" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "upcoming_trainings_score" DECIMAL(5,2),
ADD COLUMN     "upcoming_trainings_target" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "waste_disposed_actual" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN     "waste_disposed_score" DECIMAL(5,2),
ADD COLUMN     "waste_disposed_target" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN     "waste_generated_actual" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN     "waste_generated_score" DECIMAL(5,2),
ADD COLUMN     "waste_generated_target" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN     "water_consumption_actual" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN     "water_consumption_score" DECIMAL(5,2),
ADD COLUMN     "water_consumption_target" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN     "water_quality_test_actual" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "water_quality_test_score" DECIMAL(5,2),
ADD COLUMN     "water_quality_test_target" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "workforce_trained_actual" DECIMAL(5,2) NOT NULL DEFAULT 0,
ADD COLUMN     "workforce_trained_score" DECIMAL(5,2),
ADD COLUMN     "workforce_trained_target" DECIMAL(5,2) NOT NULL DEFAULT 100;
